### ISSUE TITLE
How to enable autostart of gitea on synology

### ISSUE THREAD

**Issue by alsmnn** [jboxberger/synology-gitea-jboxberger#2]
Hi there,
first of all thanks for the great work. Gitea runs flawlessly on our Synology, except for the autostart. When I reboot the synology, gitea isn't showing up automatically. Is there a possibility to config synology/gitea so it starts automatically after reboot?

Thanks in advance,
@AljoLe

**Comment by jboxberger** [comment]
Hi AljoLe,

this is already the case. After reboot Gitea start automatically. Which Database Backend do you use? 

Kind Regards

**Comment by alsmnn** [comment]
Hi jboxberger,
I'm using MariaDB10 as a Database Backend.

Best Regards

**Comment by jboxberger** [comment]
Then i think the problem is that your database is not runnig or is not ready for service at the moment Gitea is starting. I am using SQLite and this works fine. 

Kind Regards

**Comment by alsmnn** [comment]
Thanks for the info. This issue can be closed then.

**Comment by jango-fx** [comment]
i'm having the same issue: gitea is not starting after reboot.
i'm using MariaDB10.

is there any way to check if the database is running during startup (it is when checking via DSM)
or is there anyway to check/change the start-order of different services?
