### ISSUE TITLE
DS1618+ support (denverton x64)

### ISSUE THREAD

**Issue by wtswartz** [jboxberger/synology-gitea-jboxberger#3]
I'd love to give this a test on the DS1618+ (denverton x64)

**Comment by jboxberger** [comment]
Here is a modified Version. Take your time. If this work i can implement ist in the next release for you.
https://drive.google.com/file/d/1rDbyTsMevlim9dA7uGc7oVEkWXamMnAh/view?usp=sharing

Kind Regards

**Comment by wtswartz** [comment]
This appears to be working fine. Installation was flawless, I created an account, made a new repo and pushed some commits. Thank you Juri.

**Comment by jboxberger** [comment]
You're welcome!

i've added denverton arch to the master branch and it will be included in the next release. If the next release works fine for you, then we can close this issue.

Kind Regards.

**Comment by jboxberger** [comment]
Your arch "denverton" is now included in 1.7.1-0100. 
Kind Regards
